services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend-api
    networks:
      - f1-network

  backend-api:
    build: ./backend-api
    ports:
      - "5282:8080"
    networks:
      - f1-network

  data-engine:
    build: ./data-engine
    ports:
      - "8000:8000"
    networks:
      - f1-network

networks:
  f1-network:
    driver: bridge
